blank_issues_enabled: false
contact_links:
  - name: misonomika.dev on Discord
    url: https://discord.com/users/898521048545374248
    about: Message the maintainer on Discord.
    
  - name: yuneko.dev on Discord
    url: https://discord.com/users/721746046543331449
    about: Message the maintainer on Discord.